import {
  FigmaFileResponse,
  ExtractedFrame,
  ExtractedColor,
  ExtractedFont,
  ExtractedComponent,
  FlowConnection,
  TemplateType,
  MarkdownTemplate,
} from "./types";
import { hexToRgb } from "./figma";

interface GenerateMarkdownParams {
  fileData: FigmaFileResponse;
  frames: ExtractedFrame[];
  thumbnails: Record<string, string>;
  colors: Map<string, ExtractedColor>;
  fonts: Map<string, ExtractedFont>;
  components: ExtractedComponent[];
  interactions: FlowConnection[];
  fileKey: string;
  template?: TemplateType;
  effects?: Map<string, { type: string; count: number }>;
}

// Pre-built markdown templates
export const MARKDOWN_TEMPLATES: Record<TemplateType, MarkdownTemplate> = {
  minimal: {
    type: "minimal",
    name: "Minimal Spec",
    description: "Essential screens, colors, and typography only",
    sections: ["overview", "colors", "typography", "screens", "instructions"],
  },
  full: {
    type: "full",
    name: "Full Specification",
    description: "Complete spec with components, layout, effects, and interactions",
    sections: [
      "overview",
      "colors",
      "typography",
      "components",
      "interactions",
      "layout",
      "effects",
      "screens",
      "instructions",
      "assets",
    ],
  },
  accessibility: {
    type: "accessibility",
    name: "Accessibility-Focused",
    description: "Emphasizes accessibility, component docs, and semantic naming",
    sections: [
      "overview",
      "colors",
      "typography",
      "components",
      "accessibility",
      "screens",
      "instructions",
    ],
  },
};

/**
 * Generate markdown specification with template support
 */
export function generateMarkdown({
  fileData,
  frames,
  thumbnails,
  colors,
  fonts,
  components,
  interactions,
  fileKey,
  template = "full",
  effects,
}: GenerateMarkdownParams): string {
  const selectedTemplate = MARKDOWN_TEMPLATES[template];
  const now = new Date().toISOString().split("T")[0];
  const topColors = [...colors.values()]
    .sort((a, b) => b.usages - a.usages)
    .slice(0, 20);

  let md = buildHeader(fileData, fileKey, now);

  selectedTemplate.sections.forEach((section) => {
    switch (section) {
      case "overview":
        md += buildOverview(fileData, frames, components);
        break;
      case "colors":
        md += buildColorPalette(topColors);
        break;
      case "typography":
        md += buildTypography(fonts);
        break;
      case "components":
        md += buildComponentInventory(components);
        break;
      case "interactions":
        md += buildInteractions(interactions, frames);
        break;
      case "layout":
        md += buildLayoutGuide(frames);
        break;
      case "effects":
        md += buildEffectsGuide(frames, effects);
        break;
      case "screens":
        md += buildScreenInventory(frames, thumbnails, fileKey);
        break;
      case "accessibility":
        md += buildAccessibilityGuide(components);
        break;
      case "instructions":
        md += buildBuildInstructions(frames, topColors, fonts);
        break;
      case "assets":
        md += buildAssetChecklist(frames, fileKey);
        break;
    }
  });

  md += `\n_Generated by **Figma→Markdown Generator** · ${frames.length} screens · ${topColors.length} colours · ${fonts.size} font families · ${components.length} components_\n`;

  return md;
}

function buildHeader(fileData: FigmaFileResponse, fileKey: string, date: string): string {
  return `# ${fileData.name} — AI Build Specification
> Auto-generated by Figma→Markdown on ${date}  
> Source file: \`${fileKey}\` | Version: ${fileData.version || "N/A"} | Last modified: ${fileData.lastModified?.split("T")[0] || "N/A"}

---

`;
}

function buildOverview(
  fileData: FigmaFileResponse,
  frames: ExtractedFrame[],
  components: ExtractedComponent[]
): string {
  const pageNames = fileData.document.children.map((p) => p.name);

  return `## 📋 Project Overview

| Field | Value |
|-------|-------|
| Project Name | **${fileData.name}** |
| Total Screens | ${frames.length} |
| Pages | ${pageNames.join(", ")} |
| Components | ${components.length} |
| Styles | ${fileData.styles ? Object.keys(fileData.styles).length : "N/A"} |

`;
}

function buildColorPalette(colors: ExtractedColor[]): string {
  return `## 🎨 Colour Palette

${
  colors.length > 0
    ? `| Hex | RGB | Usage Count | Opacity |
|-----|-----|-------------|---------|
${colors.map((c) => `| \`${c.hex}\` | ${hexToRgb(c.hex)} | ${c.usages}× | ${c.alpha}% |`).join("\n")}`
    : "_No solid colour fills extracted_"
}

`;
}

function buildTypography(fonts: Map<string, ExtractedFont>): string {
  return `## 📝 Typography

${
  fonts.size > 0
    ? `| Font Family | Weights Used | Sizes Used |
|-------------|--------------|-----------|
${[...fonts.values()]
  .map(
    (f) =>
      `| **${f.family}** | ${[...f.weights].sort().join(", ")} | ${[...f.sizes]
        .sort((a, b) => a - b)
        .map((s) => s + "px")
        .join(", ")} |`
  )
  .join("\n")}`
    : "_No font data extracted_"
}

`;
}

function buildComponentInventory(components: ExtractedComponent[]): string {
  if (components.length === 0) {
    return `## 🧩 Components

_No components extracted._

`;
  }

  let md = `## 🧩 Components (${components.length} components)

`;

  components.slice(0, 20).forEach((comp) => {
    md += `### ${comp.name}
- **ID:** \`${comp.id}\`
- **Type:** ${comp.node.type}`;

    if (comp.description) {
      md += `\n- **Description:** ${comp.description}`;
    }

    if (comp.variants.length > 0) {
      md += `\n- **Variants:** ${comp.variants.length}
${comp.variants
  .slice(0, 5)
  .map(
    (v) =>
      `  - \`${v.name}\`${v.description ? `: ${v.description}` : ""}`
  )
  .join("\n")}`;
      if (comp.variants.length > 5) {
        md += `\n  - ... and ${comp.variants.length - 5} more variants`;
      }
    }

    if (comp.layoutInfo) {
      md += `\n- **Layout:** ${comp.layoutInfo.mode}${comp.layoutInfo.hasAutoLayout ? " (auto-layout)" : ""}`;
    }

    md += "\n\n";
  });

  if (components.length > 20) {
    md += `\n_... and ${components.length - 20} more components_\n\n`;
  }

  return md;
}

function buildInteractions(
  interactions: FlowConnection[],
  frames: ExtractedFrame[]
): string {
  if (interactions.length === 0) {
    return `## 🔗 User Flows & Interactions

_No prototype connections detected._

`;
  }

  const frameMap = new Map(frames.map((f) => [f.id, f.name]));
  let md = `## 🔗 User Flows & Interactions (${interactions.length} connections)

`;

  interactions.slice(0, 15).forEach((flow) => {
    const fromName = frameMap.get(flow.fromScreen) || "Unknown";
    const toName = frameMap.get(flow.toScreen) || "Unknown";
    md += `- **${fromName}** → **${toName}** on \`${flow.trigger}\` (${flow.transitionType})\n`;
  });

  if (interactions.length > 15) {
    md += `\n_... and ${interactions.length - 15} more connections_\n`;
  }

  md += "\n";
  return md;
}

function buildLayoutGuide(frames: ExtractedFrame[]): string {
  const framesWithLayout = frames.filter((f) => f.layout);

  if (framesWithLayout.length === 0) {
    return `## 🏗️ Layout & Constraints

_No auto-layout information extracted._

`;
  }

  let md = `## 🏗️ Layout & Constraints

Screens with auto-layout or responsive design:

`;

  framesWithLayout.slice(0, 10).forEach((frame) => {
    if (frame.layout) {
      md += `- **${frame.name}**
  - Mode: \`${frame.layout.mode}\`
  - Primary Axis: \`${frame.layout.primaryAxis}\`
  - Counter Axis: \`${frame.layout.counterAxis}\`\n`;
    }
  });

  if (framesWithLayout.length > 10) {
    md += `\n_... and ${framesWithLayout.length - 10} more screens with layouts_\n`;
  }

  md += "\n";
  return md;
}

function buildEffectsGuide(
  frames: ExtractedFrame[],
  effects?: Map<string, { type: string; count: number }>
): string {
  const framesWithEffects = frames.filter((f) => f.effects && f.effects.length > 0);

  if (framesWithEffects.length === 0) {
    return `## ✨ Visual Effects

_No effects (shadows, blur) detected._

`;
  }

  let md = `## ✨ Visual Effects

`;

  if (effects && effects.size > 0) {
    md += `### Effect Summary

| Effect Type | Count |
|-------------|-------|
${[...effects.entries()]
  .map(([type, data]) => `| ${type} | ${data.count} |`)
  .join("\n")}

`;
  }

  md += `### Screens with Effects

`;

  framesWithEffects.slice(0, 10).forEach((frame) => {
    if (frame.effects && frame.effects.length > 0) {
      md += `- **${frame.name}**: ${frame.effects.map((e) => e.type).join(", ")}\n`;
    }
  });

  if (framesWithEffects.length > 10) {
    md += `\n_... and ${framesWithEffects.length - 10} more screens_\n`;
  }

  md += "\n";
  return md;
}

function buildScreenInventory(
  frames: ExtractedFrame[],
  thumbnails: Record<string, string>,
  fileKey: string
): string {
  let md = `## 📱 Screen Inventory (${frames.length} screens)

`;

  frames.forEach((f, i) => {
    const bb = f.node?.absoluteBoundingBox;
    const fills = f.node?.fills?.filter(
      (x: { type: string; color?: { r: number; g: number; b: number } }) =>
        x.type === "SOLID" && x.color
    ) as any[] | undefined;
    const bgHex =
      fills && fills.length > 0
        ? (() => {
            const { r, g, b } = fills[0].color;
            return `#${[r, g, b]
              .map((x) =>
                Math.round(x * 255)
                  .toString(16)
                  .padStart(2, "0")
              )
              .join("")}`;
          })()
        : null;
    const childCount = f.node?.children?.length || 0;
    const childNames =
      f.node?.children?.slice(0, 8).map((c) => c.name).join(", ") || "";
    const thumb = thumbnails[f.id]
      ? `\n> 🖼️ Thumbnail: ![${f.name}](${thumbnails[f.id]})`
      : "";

    md += `### ${i + 1}. ${f.name}
- **Type:** \`${f.type}\`
- **Node ID:** \`${f.id}\`
- **Dimensions:** ${bb ? `${Math.round(bb.width)}×${Math.round(bb.height)}px` : "N/A"}
- **Background:** ${bgHex ? `\`${bgHex}\`` : "transparent/none"}
- **Direct children:** ${childCount} layers
${childCount > 0 ? `- **Layer names:** ${childNames}${childCount > 8 ? ` … +${childCount - 8} more` : ""}` : ""}
- **Figma link:** https://www.figma.com/design/${fileKey}?node-id=${f.id.replace(":", "-")}${thumb}

`;
  });

  return md;
}

function buildAccessibilityGuide(
  components: ExtractedComponent[]
): string {
  let md = `## ♿ Accessibility & Semantics

### Component Documentation

Components with descriptions:

`;

  const docsComponents = components.filter((c) => c.description);
  if (docsComponents.length > 0) {
    docsComponents.slice(0, 10).forEach((comp) => {
      md += `- **${comp.name}:** ${comp.description}\n`;
    });
  } else {
    md += "_No component descriptions available._\n";
  }

  md += `

### Layer Naming Conventions

Semantic layer names found (state, size, semantic prefixes):

- **State layers** (hover, active, disabled states) → map to CSS pseudo-classes or component states
- **Size layers** (xs, sm, md, lg, xl) → responsive breakpoints
- **Semantic prefixes** (btn-, icon-, text-, bg-) → component type hints

`;

  return md;
}

function buildBuildInstructions(
  frames: ExtractedFrame[],
  colors: ExtractedColor[],
  fonts: Map<string, ExtractedFont>
): string {
  return `## 🏗️ AI Build Instructions

Use this specification to build the full application. Follow these rules:

### Tech Stack Recommendations
- **Framework:** React (with TypeScript preferred) or Next.js for multi-page apps
- **Styling:** Tailwind CSS — map the colour palette above to a custom \`tailwind.config\`
- **Icons:** Lucide React or Heroicons (match icon style from designs)
- **Animations:** Framer Motion for transitions between screens
- **State:** Zustand or React Context depending on complexity

### Colour Token Setup
\`\`\`js
// tailwind.config.js — extend with extracted palette
module.exports = {
  theme: {
    extend: {
      colors: {
${colors
  .slice(0, 10)
  .map((c, i) => `        "brand-${i + 1}": "${c.hex}", // used ${c.usages}× in design`)
  .join("\n")}
      }
    }
  }
}
\`\`\`

### Font Setup
\`\`\`css
/* Import detected font families */
${[...fonts.values()]
  .map(
    (f) =>
      `@import url('https://fonts.googleapis.com/css2?family=${encodeURIComponent(f.family)}:wght@${[...f.weights].sort().join(";")}&display=swap');`
  )
  .join("\n")}
\`\`\`

### Screen-by-Screen Build Order
${frames
  .map(
    (f, i) =>
      `${i + 1}. **${f.name}** — ${f.node?.absoluteBoundingBox ? `${Math.round(f.node.absoluteBoundingBox.width)}×${Math.round(f.node.absoluteBoundingBox.height)}px, ` : ""}${f.node?.children?.length || 0} layers`
  )
  .join("\n")}

### General Principles
- Pixel-perfect implementation: match dimensions exactly from the screen inventory above
- Use \`rem\` units for spacing, convert px values using 1rem = 16px base
- All screens should be responsive — mobile-first approach
- Implement proper loading states, error boundaries, and empty states
- Use the Figma links in each screen section to inspect exact properties

`;
}

function buildAssetChecklist(frames: ExtractedFrame[], fileKey: string): string {
  return `## 📁 Asset Export Checklist

Use the Figma REST API to export assets before building:

\`\`\`bash
# Export all screen thumbnails (PNG @2x)
GET https://api.figma.com/v1/images/${fileKey}?ids=${frames
    .slice(0, 5)
    .map((f) => f.id)
    .join(",")}&format=png&scale=2
\`\`\`

For icons and SVG assets:
\`\`\`bash
GET https://api.figma.com/v1/images/${fileKey}?ids={ICON_NODE_IDS}&format=svg
\`\`\`

`;
}
